apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd-public
  namespace: arr-stack
  labels:
    app: arr-stack
    app.kubernetes.io/name: sabnzbd
    argocd.argoproj.io/managed-by: argocd
  annotations:
    cert-manager.io/cluster-issuer: "private-ca"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sabnzbd.i3sec.com.au
    secretName: sabnzbd-public-tls
  rules:
  - host: sabnzbd.i3sec.com.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sabnzbd
            port:
              number: 8080
