apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - lazylibrarian-pvc.yml
  - lazylibrarian-service.yml
  - lazylibrarian-ingress.yml
  - lazylibrarian-public-ingress.yml
  - lazylibrarian-sealed-secret.yml
  - lazylibrarian-config-seed.yml
