apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - music-assistant-namespace.yml
  - music-assistant-pvc.yml
  - music-assistant-deployment.yml
  - music-assistant-service.yml
  - music-assistant-ingress.yml
