apiVersion: v1
kind: Namespace
metadata:
  name: music-assistant
  labels:
    app.kubernetes.io/name: music-assistant
    app.kubernetes.io/part-of: day2-services
  annotations:
    argocd.argoproj.io/sync-wave: "0"
