apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-public
  namespace: arr-stack
  labels:
    app: arr-stack
    app.kubernetes.io/name: bazarr
    argocd.argoproj.io/managed-by: argocd
  annotations:
    cert-manager.io/cluster-issuer: "private-ca"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bazarr.i3sec.com.au
    secretName: bazarr-public-tls
  rules:
  - host: bazarr.i3sec.com.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              number: 6767
