---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA+M/jzONcNmgKtuktXO+Gk1ISWcI6W7Xa2KH928iNO6V3reudwLtK+4rt2V2Tq0j1159jVHJkMTTa04Thgch6vJmbzZ2ACSDMxZOUX85UevzXkIe2w+QSbIzuPAYwmLqeA4h39wa4DNlFW7c7z1ye/BuFA7o4RtLsOZDh2+PNMVdM0fyOHleV6f0CaTHbKSLzp/4DHFTxjIOz1RiAsQTNjTklF1ZqeXd+tDFAdQdCUomEy7nIjGrh1TN1aRWcxLAwJ8E8ciAvAoGpcf8fl8nQfjNcT1+vWYGCC8r3guNa9Yq1n9R2JtmQ42jw2KWQdFNx2lBCmSIkvcagPooPBZKeKB3ZyNYsLtkf4sKqUlofZx+D6FOoTAkTP4/+7D4rti3ZcgZoJKh+lnCJRa64uZCEfaB/u9y4ABvhjZDNCGSGQRo89WgXwe0ji7BiUSjBETgP5bb5eUdYvyrdMRYGfLVUnMewyUo3tcH7gYDnMQ+owPlhhVhkywt62XdkoTACsiXKhhsOy9luB7Ms9+pOeuAUN4KVNEXAVA9SZgNSgau0ycXA1kHduVn1xykVkXtt4O+NoSducEcDb4laCkDV6wXI/JASL3E7DKAXFzR5XBSjHqW6QbLEfrJbd2Oddj1Obn+etIzk+w6qdRUdBoJEAxUNG4EmmWP+7eMvAcFy4Uik2ak6flYlZOd7QgBytpGu5SuBAUvV4wAXtgfA2pSR7aUidB6OqSEmuECl/aftb4q4bgfjh+UI0Ngz96aBi5EFPb5W3T1UCCQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
