apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - selfsigned-clusterissuer.yml
  - private-ca.yml
  - cert-manager-app.yml
  - cloudflare-api-token-sealedsecret.yml
  - letsencrypt-clusterissuer.yml
