---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgCK4lNfE8sQulYNMkQfudUg+g8nTxmJyJ0qY054iXFR0OI2s8No7wZCKWs7GLQ6bRke8WJ+nuapLKqwJal/9RKMZfKl2hoocIX1DdWHvz7iwjuiJvH9TgmOzU2XemzwCY05+G8vVUoVMVF2lTsaZmQEBM1YKDbooK0MEfkEnYy3cfPcBJFRRWqc7wnqIFbj0mLMawLWS0pPQjCjAZXH+uW0wU5TWRgFPYRuKMGWDL954j5MyYYCH12ys9bVuypGcD1vnzOrwS8ZnnsOL0a/2SC/xsLnCfdNolnUhnrd3aJy82AJ6qZg2DKm2ZTnY4GqBlCVjtIH1FPu4/1lHnbGxuxl0ylMa+GZ1d4fJFatyUTvUxi9Sz9QrEL65QUFLG9o5WZb+Gc83MvIa6s1pC1HJx0dZTjVxiI7B+GD2DoGCFmfv5NbA8U/BynN1le7lPJH3NLRQGsbUnoSJqrmBU+AbOyzR5XXVU+nljinFK+pYt/iJ6NFb5yjbJ/mGlfOeyWXNGkLUrG/JyFpr3mc7UpFO1fK96pgVp49f/z50rU6xO1djYrHHBhdCRiSIu4acyceYacitzqmswDDK6FH7yV2RZEXU6xqYtxa7kNr3xU4B3/mrsG5DMSHOW3/v8Xy9889YvJtfjkPl3dmqpNIQuh109wOZi4FAXk38NpQR+9uVd8st9mVQbFvmFnLuivQo4TFxMkWjvHpG81WWQDFVbiGUFPmqsYVSxe7+37k4UGbXRbCehhcumCDlcaW
    N8N_ENCRYPTION_KEY: AgBXy41qtev0WMoE1yce/njA7GUEAt09tJFOLbAtnkrYnfiKm3tAi0YdXs9ZOwItXgvCS7OZZwOELYGgPVozk4qf/XLUCWfx1iK3kIdcf7eb7J1ucDKHc3mTvj/yWmtZipinWnMa+kn5Swtb6Q2Ehus4e8o2AFwgGy8X8ZtCTieTN+w2sExp12OYn5Car0gbAKqp/1HSkLiTWFS39/NDM0ysEcAmeIEpFwNDFSoLlTTf05fsR6kFj+FKb3IGVXjcq8qdkdskTX18R7l3f7328Gm31QwiblbfQKlLq3T8GZrG4i+08tYT2SrNkazbw3QCvshI+IyT7Tu5y1CGvchOGIZaGG21LCVlBVoZcgox5nu7Da19LlOaV0VW7SnKCOdXw/LPyKr8R6UQJhMQASbTfOrA4yF4rE8PrbYC7/BFfh8A710T4ypR0SXX+8NdvAZvxT/8ZLlyUEVI/uFquiTgNRgSkZXVx60OrCJ1yCPKuX14epMAkh/v5DKN3AGtVdT1zjgQiKddBCkzqpXlD3MNVKB0sh6FWsqibHLxoGHY1z2hI5DsRLxTcEcP5zgDgEW6/ZPysQooBNVBBEFMKqTKYogfANfFSqIfwUxtACXwG2T0A4Z5Ja5oEZB3/HQmj+Kd1ciP1k+Jh9BZ4q5gKabb6gItMKvu3UNiZiS5WFDWJ7w4mgI3fa5xSu2RKetCysCxqpQosZ1LDAVFxYeeVS9PbH3LkEP8qu17nVrivrpFxDUSNY7At8Rxj2hJMuqI0EpiTXTpuZMO6xrwh5cG9C2V02k8
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: n8n
