---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgBeqFyNlpVVR5cua6pWZAWt1Ax7ivT4C6sZcLnYujzgW2E7kqObPDhj9ywB4eyaUo/Hop7Bd7tnZjU/vHyJTqLSyX3Yy9XyBPqzEGB33vP7UaPL9yI18o6eMyOW2R4+0GavlH2MnOU3+drDbZw6UZvcdY9LzGNQdoqx+sG4aqN9msSm9CY0diZxErnB0BVCTFG6N8Iqv7zqgssw8pS3Gafr+SNd/BApnZvCg43Y4n5jWrur6Cxsm5wX4whPsCMErq3YMqemRMI7HCbMmGluY945yJmkzUOqKE15mLxq3Xb+6wYiJpWcRMht9i4oB0g00/SETnX99iw0UEUBdy2hXnaULQu4e7wcrNo3L2DrXuIYZ9ThHSrD7bikSA8J1yCGCOF2IcYrJBAKhjfOvGkN5n0fKDBOM1qVG+m355syq8Lzv85UjXUPRYs4K23KKbpEL8b5edXh9msU+68kMf5Xqey1CcqAEnwR6Yu57ui/UCT0U3MHvYDknHviWmKU2IcxCYAHH6JHa5rmpV3ZQS5zGE3Sl9Ugkxmp6FunwGA80BaBOhANQZqOnH2EvA86c6O+Ns9ulZ0WDtN4g76dzK8w7fnGCPMdFlNIT8I9GUybbmEWaaFi8qJPMklnMEiHn5aI3Z/jnRD6ToP/faUCUyTrSPkqhIOaq+3iSaAD40U+0gdCRm9GN2wqV3AKhP1q+e8ArVTmozCDWA1013eUHjn1UkWJsrWY/33tajO+N7QiUM4IyKvqHNI/CcUQ
    N8N_ENCRYPTION_KEY: AgCZuOVu5tLlcC2oQhBsr8grClZQKAim86WQ9n4w6g+pMSjSVBKf3hfdPJl8KS7Lp+YIelMwTdke4zKNAUEaCDBEUbb+v7AKhw/le2ph4VEEYIHHwsNbqQf0t7bqKvFPwlT4mVAG9LVqL6Bl8UbMJE816QG4o3mp97IiIuwC0JlBjgFF1YuYsrY2zeiF17+r2lFual1+85qPIUILZYshEETAsxnpUIwU2Z+pRlQqyCxgkmD9fumMOkcKSEW7O9Pu6KIZUyaz/tFsXTs+5RhGPAFFvS9jyPmKsYicM2AZFBYvoqTAYtKKSMIDp4GToQ5s2nBP1ssdSNzPSeUapPVH7LUKmkmSOKA3o6G3mZsybTHsxYL0WEPkXh7/7pIuH50jj3Np5hhzkRIeWXW+IjgwBGi8mI5/2DTxnG/00di/LbxwsIxFrB77tqFuu11I641g49sWxanageE8/WrWRZMeozwnNGMeOQV3cBtEI2mekfrSOlk3sy386zFiWdTUJS/JLwrRzM5jjv9iXE8mD8tHmaD7P/+hQ82kYAhB67uz5o2eJqrDueIha4wSkFdiojT4izIKZ6+AbhSG+bxg3mOM3JSQ9edFaHGZcFwXzdYEwz4fIpf5Q9Aw0Dz4GdrBOYJIOCLz9GP1uc1P7VE7SmMq36VXai0tf5i/Pzb6pL4yR6g/IYF+INVn6+dgb0FZKRrF51548rmGcjw6TG3bOGPHHGOWe/5hrPb7aGZTJWxlcrZT1JKteA/hV7izPngObxKaNAUochLAGJMtCSCBtk/TIcLY
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: n8n
