apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - paperless-namespace.yml
  - paperless-sealed-secret.yml
  - paperless-pvcs.yml
  - paperless-redis-deployment.yml
  - paperless-gotenberg-deployment.yml
  - paperless-tika-deployment.yml
  - paperless-hepburn-hook-configmap.yml
  - paperless-deployment.yml
  - paperless-service.yml
  - paperless-ingress.yml
  - paperless-config-seed-cm.yml
  - paperless-config-seed-job.yml
