apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - arr-stack-namespace.yml
  - arr-stack-rbac.yml
  - arr-stack-deployment.yml
  - gluetun
  - sonarr
  - radarr
  - prowlarr
  - sabnzbd
  - bazarr
  - jdownloader2
  - lazylibrarian
