apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reports
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: reports
  source:
    repoURL: https://github.com/gorttman/day2-services.git
    targetRevision: main
    path: apps/reports
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
