---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-anthropic
  namespace: litellm
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgB6C0FtjXUXqmpRWdphvQSkC5uofmy/WqcIL+cfWQmJJtyxrQkyfrezF6dokvcVc5ynP6IzFxmIz24FNRJ4KyD/4mkUl5ojor8s57j3kPjgdJMAJS97rmjgnwSkmojeSNG4SD7WVY7wSnRO3uJvbCug3rVnbjqegfR3Qg0BVKKSxUEjgpXrBA7WhJxAonYMgFZsUFOK8FUKs1cq2IHebPr+3mYEiLVP/3HverlnE/CjcoQbXuqcjGyv6rJ7k5wCIoW6qj1J1oH8QbK323kP8HF4SgZtFUWuSGVN23BswwpQJKhtVZ657TsStlMEsICtlYEVtwVjdv7uNwHZ6P+0X7vjvwMS9+iR7YAEHeW3co3pdVoJHsLsPgnOws64fxZEQuMWkQC+WimyZAlUk9XpLc2XuRnkOXuaTPrXYkwB4zx+oF3wsljZupPr959aeSxjWObxBaqtgaBDzHIF89AT66MG6T3UKlysEXz9grzOou849z3N9TFFcVCm5VkYja1Yb3TSliwtIdfFGVed3Ff43IOh5OYsXwfU0kwPgqxwMKhF7KzDtGqJd75ZJ+EQuNKVL8zSb8VHrk3SxMppfc2PxiqKcaayi8SWA1LlcpbbEe5J6kN+MVSnLIbufj05xm1JHMIh/5U1J8YyKJru6Oc1OmeGt/tmG41b7vRJF+OIz6hR3LQtslt2PCNpxdkBYDVRMVZNjZWFay1ZZt72DuogPq269e47MWkzpTmmGhWRRjMVZC6kvOmJ1Mld7JWrGjHG6mTxuV/XZd2XG4bmOjH5v9skg1TqPv+T5GnmykEc1NXOD9JG3AFtm9+7x+LM5F909DX5lD6BoDw95KZDst8=
  template:
    metadata:
      creationTimestamp: null
      name: litellm-anthropic
      namespace: litellm
