apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - obsidian-namespace.yml
  - obsidian-pvc.yml
  - obsidian-state-pvc.yml
  - obsidian-sealed-secret.yaml
  - obsidian-deploy.yml

patches:
  - path: affinity-patch.yml
    target:
      kind: Deployment
      name: obsidian
