apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-vault
  namespace: obsidian
  labels:
    app: obsidian
    app.kubernetes.io/name: obsidian
    argocd.argoproj.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-static
  volumeName: qnap-vault
  resources:
    requests:
      storage: 10Gi
