apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - immich-namespace.yml
  - immich-sealed-secret.yml
  - immich-pvc.yml
  - immich-ml-pvc.yml
  - immich-redis-deployment.yml
  - immich-ml-deployment.yml
  - immich-server-deployment.yml
  - immich-ingress.yml
