---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inbox-router-secret
  namespace: inbox-router
spec:
  encryptedData:
    N8N_WEBHOOK_URL: AgC67hPcPnpmJqFdU+QWfCDeyJN0rFzvOjDqGMnGnDB0kJnqLpIZNNDTkPqlLn+knA71wAnp3bzFybbipD7ReFoF4iRBeWQIx/0Mv4O1qaE/jwrFU/ycKq9yBav+caTVPiIb0z8Pxi/1wC6YJ80ZsDDWnV7BjC/ZlWLqVbtywprYiyV+3283vK4PluvAuPnjJgZ0HGlGl5Wh+yHrGtvBT0XYA/c90DNPxN244Hsw7jf3x1z98BZQ9E9VwxCBgJDPHBKjqiBC97VQF/Al+/5i5lkl9Ol0nVIJZV3Hi29sHj1ZfTcUM7U9z4luXGaF1B0y8d3e1rUIm1QuhqOgIEeQqjLFAwxJplnHcY585UVPvyvI/UaTFCLxtmKvBfYyzZvq09pBHD6ON7cUMIIi4nr4/l/aQp3VYzbL3ZDhkoL9BHXUDmBipv+dACi9VOWxw2mvYiVUnCS6/PgCCzE4yDdqyFiSoe532iaKXbc88gBRrZJJo7o/Hvr5Y9Y52G3ebEkE1ZhsnCV+2foEA5gvJyv7zuZwCejbiHIFfNfmj8g/mdzqSqomVgpDCepN8txeAQjUKEMhK/YNgvCF3MzyfNa4Mcz+V3xfng31cqCFjOppDi4h/BRFomId2yYuksAtnLjXSODjDRcuSVa33pAo50HCwtGPco3WDb+jb3xblMG2K+CrbmJmG0PikD5teAHKgWqyeUZi9BTYBC+6h2Zf0djYjMtJy1nmIQvnAnzbyupkOo4Ntqjf40+EHUojNlUVtgTKP0Ts7NWh1Nv1Vg==
  template:
    metadata:
      creationTimestamp: null
      name: inbox-router-secret
      namespace: inbox-router
    type: Opaque
