apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - inbox-router-namespace.yml
  - inbox-router-configmap-script.yml
  - inbox-router-configmap-routes.yml
  - inbox-router-cronjob.yml
