apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - movie-status-rbac.yml
  - movie-status-cm.yml
  - movie-status-deployment.yml
  - movie-status-service.yml
  - movie-status-ingress.yml
