apiVersion: v1
kind: Service
metadata:
  name: movie-status
  namespace: arr-stack
  labels: {app: arr-stack, app.kubernetes.io/name: movie-status, argocd.argoproj.io/managed-by: argocd}
spec:
  selector:
    app.kubernetes.io/name: movie-status
  ports:
    - {name: http, port: 80, targetPort: http}
