apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vpn-healer-rbac.yml
  - vpn-healer-script-configmap.yml
  - vpn-healer-git-deploy-key-sealed-secret.yml
  - vpn-healer-cronjob.yml
