apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vscode-server-namespace.yml
  - vscode-server-pvc.yml
  - vscode-server-secret.yml
  - vscode-server-deployment.yml
  - vscode-server-service.yml
  - vscode-server-ingress.yml
