apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vscode-server-namespace.yml
  - vscode-gorttman-pam-cm.yml
  - vscode-gorttman-deployment.yml
  - vscode-gorttman-service.yml
  - vscode-gorttman-auth-deployment.yml
  - vscode-gorttman-auth-service.yml
  - vscode-gorttman-auth-ingress.yml
  - vscode-gorttman-middleware.yml
  - vscode-gorttman-stripprefix-middleware.yml
  - vscode-gorttman-trailingslash-middleware.yml
  - vscode-server-ingress.yml
