apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-server-data
  namespace: vscode-server
  labels:
    app: vscode-server
    app.kubernetes.io/name: vscode-server
    argocd.argoproj.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
