apiVersion: v1
kind: Secret
metadata:
  name: vscode-server-secret
  namespace: vscode-server
  labels:
    app: vscode-server
    argocd.argoproj.io/managed-by: argocd
type: Opaque
stringData:
  password: "changeme"
