apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - qbittorrent-pvc.yml
  - qbittorrent-service.yml
  - qbittorrent-ingress.yml
  - qbittorrent-public-ingress.yml
  - qbittorrent-config-seed-script.yml
