apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-namespace.yml
  - postgres-sealed-secret.yml
  - postgres-init-cm.yml
  - postgres-statefulset.yml
  - postgres-service.yml
  - postgres-adminer.yml
  - postgres-books-db-init-configmap.yml
  - postgres-books-db-init-job.yml
