---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-superuser
  namespace: postgres
spec:
  encryptedData:
    PAPERLESS_DB_PASSWORD: AgCjskcdoyLebgyPCsXlnifv1cyXCvKBpquEKp0j0IJqCEodY6FgqMJ/7EP121j/v0d0y21V1G0VDVyD52jIhEr+hcN0gAUPFKJ7k0ia5cx8r1HjqKWuaGmPECxdFtNdYkMrhW5ixtAAoRzjUoyxdyR5s1dgRPePI/o/nd40LW+WWf0TuAtvu9Lv6nu1A9PHK6ObboEcaviKFnLokfIFZkyYi4MRL/5eFdu/fvPkHo9SuIdm7n7TjIoZ5ycxjAkxnHVLBhttzgDEwBpd9hn/vtcqi0yddvCVCmfZg7lOP6IklwZMIibVU2/T53LkmR5r+AG/iWxlphAIdvgeTkX/R9BE1HI3KtwnZslso22NqUbCFlF5Ig8YJiRGfEaxJ7nVI6i7ZFMGumqH0qhnHuNFOO4K8yYo2VXfnJHCuGxbglCzwm6Md0WuQS77lGVsifFQj+avnwjPrTAeL72r4AFCVnduVanoxG/LCaKuMD8ePUWrk5t5zeeFCRk3vOAERcLUOQWQbGoWKO8p+STBOXewk9xH8Dt6yuimOpGuANb/evpGcwCyLiQ6dNufTQOoj9xmLLTT4cH3fP62vHvQA+IAJRIoFXa07q7Qxz7Bnw3JwoWcb+fQ7fJcCWVBOB1dj8G9hks/EdMCImDk69Kj1BdLCU7j5lT5uSNVDX9jjoUc6U6XD6eRWUe5//TqXl/lBbViTaI2VhfH/3/XtCxQ3t05jQVnWNRg+fPoqsOv8me3
    POSTGRES_PASSWORD: AgA6BYsaXpai+wek+CFm73ZMTQjfmBffXUhU3oYMyLAs6GgXnhmSBUGJo7Q+40nRzh8IafgUOT80E2Dl3TDy9Ya5J6G/RerFVUFKTib0X/sCBhe6ykJSGdrNRtrWsGL+O3UMan595ITNhM9dfxpBKrrUtGEPuVmg8QElV+TDYQ0lqUsycJbryQ6na5qbYsxyBbtCbEdS3r8Pxrwy6Rui4MMJwWLb6m5NsMBxvClE6F8xngwY23GvewS0H73q8NxN05eYH5fAj2qJcGxxrwrviT4vitA+MZ8ZZ01IU/MhosZCPjiOPiXgT5R788HJKNdjrJVe05OkNOKYfj8jw7coGCphrj1o0u0dXRxIaJuFfgNx0tIGKLclh0ejNbDFCXXAlUErvok6KDdnkXxyUWN6WW94kDFudrLiogvx+c+qA0NyySAeBXWrQtCzxAG99tB8j/XMJXND/CQiFXbzf9XxjURJ1mmggSfHjtEiMM5NKrbS/b3keHTPo5F7kcWCUC/laco21pS65nVNUjic+06c+cP1GXsJHytIUCc841VrASoDzq5R3L6HvMRtGaAZB5JP4ia4+7jxF3hJ8VLdd8Ax8tl/89qL/hE+MgtKeCgxi+Xz/RjHiSxAIsOxGVN/U9IcVoop2uS0tpK4yd8JAARRUNevSRiWASsyJ1p+YvmghYtH31050eA4qnbZjDVLSxalGm5vhdBwDpJfghHtd27LJ5bTb8WAoTl/WGSLWNxs
  template:
    metadata:
      creationTimestamp: null
      name: postgres-superuser
      namespace: postgres
    type: Opaque
