apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pihole-namespace.yml
  - pihole-configmap.yml
  - pihole-pvc.yml
  - pihole-b-pvc.yml
  - pihole-deployment.yml
  - pihole-b-deployment.yml
  - pihole-service.yml
  - pihole-b-service.yml
  - pihole-ingress.yml

patches:
  - path: affinity-patch.yml
    target:
      kind: Deployment
      name: pihole
