apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
  labels:
    app: pihole
    app.kubernetes.io/name: pihole
    argocd.argoproj.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi

