---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homeassistant-recorder
  namespace: homeassistant
spec:
  encryptedData:
    HA_RECORDER_DB_URL: AgDPmmhT21K3si2rvv5aJDXhku0vXjlaE7KexIAFnsgEcNLJ2S6vYtlKI+9tUfuNgQEkqrGEBsjB2yp5o+2pn69jd81lQL5OKep3+jAKoSLXGOEDRE6geUesR+AQ62PHTOehtyYWi6cM0E/WOQiOoqiHhuJ85SmjgJ0iDVjKWL7Z22msS5MxSBkvdJPQaPelXLpyDU4mJF8KF7Pi2TnxDACgqlLO6GWE03RVk8GxVvVXBYsm6zGdduMtTHsR9wf5lEJ5/wFUP6r46txavjjd//u4hRBaUh0hl4hXEy8ILp2AZzrULdhouIjuppPQsQmjXB/0TOqMOTBamoZHoiQosrfbxxE4I/ODh1DLMqIs+JtyRqHt+0cmtAE3mYZdSLUpYL5OMLz/uf9nLj+5Wi+6ncH5fJY1JLgUQzmtbAOPuuHxZHKoIEG8fG0VjIm1kpGYhGIBSewPhTIACPw9FXZzJ8t2bmt+7BtEkax8OyVRnOS3KOD4aA4Z0bNLHiZff3OPm2KlFs0HFn9AkrbF9jN8ZK76TlVu/XU3d29fuwLgCiSuCBL7SV70SdOIV0PC3xUUP03pfOeyE6d4hq3jOj8/JwQfVmw3xBQEeO1Va9BAYMwsvY3Hrloi2Xe7IbcEPcGHPUEDIYnlCKBeS39ZFt6pCxKVIK3ovwnnsnP3Ntb428TZsVdtdU/shl9CRlxC5PurY2kJ+2OuYFpwGHM8lNKuMEB35cwwPXbzinmar7vvJPp9C95op/zlrAXeVbSoqowTkjsQCYNWFVTy1Bek9eKA5xEZ1n9YSi4YzdqUa787EwK073Yrg7wdYOtfXNg3zisapayPRhyzrEE4OQpGj72z41vT6F/htB3ikuTYNw==
  template:
    metadata:
      creationTimestamp: null
      name: homeassistant-recorder
      namespace: homeassistant
