---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homeassistant-recorder
  namespace: homeassistant
spec:
  encryptedData:
    HA_RECORDER_DB_URL: AgAwmFfmdXMlzY7uaLrp5hFH120nL3DNTeTQjksKwghHsM1v+yABAngo+SdrTbxK21014EeX6O7Ph2IKx3YHmm7uTcsHYVqPX7eJ+8a1irV8Iu9qfYrXeQFGG0VP1S0Rydod7Sq/TsT/H4I152hcMrDPF5Z5tTU+zelDyIzcNZeBociwB23eEnazuMcTrcXZ7LorDj4flGkjUYjfkbTdURSJv69mCODpARIJApzF7RO0/h02/85n2FYZ3WzZ3x+4PCesbK3xEkPbjKCX0N3V9MHDrHv5uKUesSVB4n8clDIf7EcEelRS3b8qfF1F2MGOWZ4yZokb3ZMcrpoAj1I6xHWDUr8Oi29jq7rVYGI3O1n16Gs7Y7NlZZGgcie96iNraKmuQjtXWTF/FVO67nH+y+BiD881rXljWN0L2yBvKkv6QvMKzzP5pbFGvbu+a3OU7wKSE2KIo+ONyvhRVqou0Zsp7nOI3/D/Fh6BDoMyTVKX7v/lmEzgcHEJSP10Tw1TxlipWRQ5k8wfSkvwnZhamZmPKfo5L3+A87oWEkoqxGVJEeotedVB2TGX9CgnrM8N08wsrxvGbfTRk466ukfWVvv2hoQKkdofC5H7bQxMv3V0d8qGrjlrYvisR1Y5tzOjRt45fW2LhOVa2v7ZiiwnxlR4+Q/sQ0oeLjkgR9AT2aNY6CJaHcCJHpupJU5qpJNQXlo55sWVLvYMLmnUhKPbLHMWuOkpTBa2dTWy/EUa8uTfwrfG/kVMUU4vURWEpfm4Co1Z01gl26sXTYPAjv2xdABLEGt19Z4EpKGhM8lYHGv3dxUYTCAntMH4VUiXlp14JprwkN3b9tCrWUvjOUHvEWv/TW4OdMRcgSkfVw==
  template:
    metadata:
      creationTimestamp: null
      name: homeassistant-recorder
      namespace: homeassistant
