---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-tagging-secret
  namespace: default
spec:
  encryptedData:
    IMMICH_API_KEY: AgA7Xv7vq111a7gmk/ierLlcLhg5BjZwx7OrrEvCDc5SO5FPfo7JlT+2yHEA5JatcXdYjORG2wh8BuezSOh3Hn6vfmCxyTwWRFpX7QwjFYlE9PP/bTGM6pvc9YVDqLHnada0+bZx/KOyyqybxpslchoSNgCda9foaPtjhbmXm5fOdszToyVpEDMM+R1asxcTtnTEioTds49YJoQNfSm/jl8RmFhTTgZvQnJXChI31ROdJGyruoVGyVwJifYPMLRKH6Nzld8P8CaZKAMRA9cFunwE5hBxhVdQyEOZ5E5bmJNDYAP6UpAUbm2jjIJEa1WkQyHNOxN+BgnSiWIIDnvkUEpLvZZHmHXJU8sHYZeR+vAidlFw8AnCYYSP/0NUYBi1lWnvb9cM7QqSRQ3JDTwGDMTnDVqFS1nUcloaEYZIEo6LFggvlDs43+SJwaHyMoYS6flF1bEean5WGA151Bn68DQnsHWYrlJSU+IdJOVbhx7OiYbIJSyehD7Lkebmo94EBGqd8Hwxqirx14EHL8XueMxD1DRkhwRh7Zh2DIXHX3C2Z4z75D5kpA4/4fGzSAzPbIw+n3B0yT1pyg93aG+gR78sE8w7uhdHAaMAZKTlYiTBmJ3F0H0LlGO+jLwbTWkhpaerAX00iFQRBjm+f3Y/QK2jOxnktqUSqmNQ3q7sfX9+tObZFIjqVhBG9dqWQ1bX3tgBqEuFAut+Veco0Od0AYNDrZ1mVnllsUEw2LRnB7DGMMPOH7MepgCj6/o=
  template:
    metadata:
      creationTimestamp: null
      name: immich-tagging-secret
      namespace: default
