---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-users
  namespace: homeassistant
spec:
  encryptedData:
    MQTT_HA_PASSWORD: AgCh0Ymice9m/kv9tvmLr9QSz0OtoBHzHtL5lef9i1zH2g3mSgxaeQmTYmjBW/9h/zORPDIhBwIN7A96svUE+OtPzjY6jN3C7Ciouuv2+oj42itjZ6ayfTvMqBBNSGObNksAdoOelyjOwIIp6dTlQz8HyTFVJZbYx+LC4eD3hvV7bsi7fDABxbrVK7la+mhAw/B6dJ6Uzb9nlvJwMGvBAD/43sOYMvJsqfS6T/S9hjNpQyWyWVza6j/8EBlGFGnawBPJYGQ0HvgsHLCFlNBQJa8rX7HKen7TgU98Rr9wU1XOzUvgdAIYBVSJncSp59/Yj+I2YOp9jWvwO1BtGT7vu03S4AyOHte9Ym+znn2wUPQpDdu9Pc4Uq9M62BXDQfJ6otQm+4W2xIm4Zt6a4kYM8XX9yS9OoC6QQyXRVJR7PAvtoXtST1+FR09t1ZmxJa9IXCrMpbOwLK0lajlvPQXtZS2DESQJpWo/7m5wqKdL42p8wxXbE6bGxPgvDI9QM5dxOqJM5Nl6qxoThYEfSAFUEbjPbwpS5fAevPHhlrnRGHthPN1eeGbR7IaAmuFdIdLSmqrKZ7LwfXy4TwoblLYg/+d7Dirb2yx0nMeWWMHmW/n2GXVT6MSDaPpuJInDRrpjPO85MaD9Fg+paIzFVKeVZo1lAybZCc55dIxMss9ZVxFpi6q/AFst0I1LtdXi4Y92NMbB1LUEy8CkhUAv3tDlYNZyGhh31NEB53fVs+kimDXimCs+jk2so9gG
    MQTT_Z2M_PASSWORD: AgBobago/zJoXwzgqjdJZVqs9oP5nI9r2zZDWgc6IKdgKiFSucIgJ+9+SGIHjVPsJb41uWQ6ZJzK6P9Pv1taj5LQ2WSK/BB6Uzhh498d28WW4gvBWZUtPyHZbnOrajDwH0TMMW+82IDgmBJDSnywKg/wsdwSMdA7xkC+Fm/QvBoNrhYbfMR+ACRgKMl4JTzOkEPmZFfeKoy6uNnDOeG3TxWAJhlUmKddrxEe5UzvkzLjapFRdVy4+lS6rlcizilDvnCC2cIzEZYQY1xBf6zsmP52QNvSU2kkg4bes/1VzaypVhfmPpusEMH+wQf/ja35zd3J5m4YQKnLgRO5wvW85T6abb4Wc2zDrjvqaMATN94oQ1mNrbaGf2F7CndfJcWv+H2ZfnOtSMEUP1k9YixqGTO53wi5u+ssEcuExo7olWuYxiMVrUdBzQuzp3gzwa9NipOdd+LOE6b7SmoAhbF7uuA5TxVaz23GIWMZxnNRh6YUwxT9lMsyWp91KM6eVwo4a3YuJ5xb9aDJFKfOytHBCHhzuPAqFGbZcCAuanGQsE3KaOOEOggYQrZofgE8Fp3mBBiZmSHL07OrfEIBbBdtcRHLqVaWOuR1k+pUcf2wjGevb4NrfinEdcYFvuXUvgRybA9aRlhabjpApwCGUtcOlHyly4dNU1F7o81wMKyT+xXcbL02DGZ+x9jNho9ugOf05DkrcEGeOL+51QwYBbMyXSLEh0qWmDVwV0V1qlUBiLdMgqogRadpd/0L
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto-users
      namespace: homeassistant
