---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-users
  namespace: homeassistant
spec:
  encryptedData:
    MQTT_HA_PASSWORD: AgADWZoWQgoFyHq9el6Osp+F30bR/QGOzbm+QFjFH8kQVslY7B6DWv1jSPhm7iRnWSvl3ha9S3At5ukOv3Oqwcaey64sFYZxjSecAmv0YEQvyirAr82lxhCiKsRoAsYnqiQgtlPJJ16yKe6S/EpDhofwBkRA8d1mc+2xCX0wmTRfDS7bXsF/Zin/E+YW7quH0aiPRIRy+ZWN8oHAX9/F1C5uY9p525vpbGHGv6qo0qJYhp+uKo9/nhKTpKTLu0AB0dYphF4SAcnmxcKb0RAJhkeJpE8oYqEavWVgE5c2wmxcxCdglV1X07y1NmUz1lTXVnuRVmss9kXO3QeRni/OsXp2axziyCxBAPa52EeeOReaBEMyvPjMeKjJKfO35gR92iZbYdH/7sNNZYLHsykdJsqcCuz1nMli8j3ZkmFU+UwOmXYi9cO2GqYa37Au+jkG2q9uLuWk+DD9VO3q3OLK7lkkc1TiGCbBvnnn+eExP/G/rPX0vRZ4BP9brkXKuHc8fwEV419rV5fPpRbZA2wSwQxV+oNtmHVzJtPDMsGDsW12F6ArjzhsmCb0+5CdNOEwaXeG1+QMnJiazjV+24LBpnnYVPzfwUe+/thZG5HC+XwJ9cZ2aD8E6LFa7LqGHRQvPdhFdkM9+0WiCQVtKcMr+c+n+MpIIBIcvzJcOxq9ZVtJGI2sbYZDDkw4cUPbPmqcBkjDN7+IJospeUbAimIyosZ2Y4FZOyQ5fMsTsB0Re8L4KXf364v/b/50
    MQTT_Z2M_PASSWORD: AgCpME4iqTN4t3vq8OHlc6i2UVhIaSKojpXQN+xWPXbghsCczECnaQ5xJvn+YtoS4qM77UfPhj4QAxfBDN3wv6+w/B/bqKU4U3BZRiJtt5zitZyFlNXJsTQsqrfvSvAtpB6y5Ru+Yrmdf7Ew1TDLkdcjxMiri/Gbr9gTUEYGG/kTHqQZKU6WpipyOc7+7S7I0rTsvMZkVeKPc6HvIWPbV4gUBKWIfxg9d3pF6SPKqw3GKlPmSKeChAGxNTghiz//z/NwQRRNFM1iFIm0CapxipHRJsuwHxupDZijZz+VQN/h8Jv8WuMV31dNtQIUzsliD8iJ5+JrzVXdAReLepgB3kTaN/LSu4nQmIe582wPxu+IOqDF/LuKOuCZdlhjW0SE3XUPny/Pl2zFzUUginsKdRrCCrFKSeMdswUObbC43uBShOSOTTcRMCKwP2hSc6Uu9cCOAyiPlGjhBCEaqlnZyhRpk1wqpjVKZMrazyhDkyr0FV+aXmGK1vJ24AhhR4mHCAPpczN9bMJZsWLyqfFMYv/N2Pkc2kyqIzO6cICEubSFOw9vh4kET22ViZNgJsisj18Ini69e6GROZ+cwx0n7w5pwG5qnMddJaKnBgm/CQzTRic1DxWho86Okm8QVeeY0U/FR/YP7ROzrIeYQwaMFtEc7jGePRw1Ifj6dPNI2Jhs3VQfyOw9g/OQGncARt2iXVOZ47+mOrqWyOiyuCqTzG/BW1aV3yvffll4Kxqws4PIKNXxG+lyacb5
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto-users
      namespace: homeassistant
