---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: books-pipeline-secret
  namespace: books-pipeline
spec:
  encryptedData:
    BOOKS_DB_PASSWORD: AgAm7hkz6Nh3VkCVg2zB5rz2BLQ8bm92rxStCRXsFlPsnCl38jlPUhwdMFxEQMBngto1rSlujtBbVUABhhIddnrdHzQygaUGJZh69WuDeU1DnVNhmPrdzWpULZ/BXiCXHPTvQWwFrlbQkGpJAczII02t06FrUhRpGaTIaKz2YZqKqV/L3P0qqN1UAqPWj0FF/4Asd0dNbA4BX+DgzN673OUPoEYuj5zIXw0RIOlZ/tl+PYw7e3fVFztbE9v8UI+FJTl0O9kOKZ7Y0stxSsYzVmzh0+qJrFcD+r+wvNh+WYH4J/txemHtlA2RwWwEQHkIr5fhgcg+wvWK/eiRfsmDAiEggFLMiJ0XsoULL3Lvrb3YWZBT5WO7DWIAv1PFwmgIo1WeH5H/luxkxB/DGDeaITjMHeo/4sd1IlbN9XtqAeVwsQiZsmC+GyuAR5Qk7e8W+nD/7cZHm8fRhQJ0N+Nev3JhRPvzzp/Ot0r9nJDe2XRxFncDwHSvgVJllzUX1hZrhZPF6BO5gkezfqiQUHrjV2bCjVr2Ed59L6IfVb9UqAFNDz6NYNCaqqtCc2Kon9j9GxFtdqBEtoi/saPt8Zc3axdReKKbuJYUL8W9qAPdbwi3X7mlaHo3IUyC7JggX5WMkVtgIXcVtTCS5Yc0EvvdewTrolLRvZT6y5S/+X6Ft3eLxrz6kFwxYiPn4XqEEjrvlPCQFYAd6qfN2K0hsP88C1NQxkV72KSuhERUqvcfP40bgtTkYboTJN6Wqygpfg==
  template:
    metadata:
      creationTimestamp: null
      name: books-pipeline-secret
      namespace: books-pipeline
    type: Opaque
