---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: books-pipeline-secret
  namespace: books-pipeline
spec:
  encryptedData:
    BOOKS_DB_PASSWORD: AgBe2L0fRhpquBdrF89ehNwNHBLs7YBJOhtisgGt/mXs57m1o0Fw/bz0TLiRLhLtN/pp/JPbklIDNln1meCXthf2KrKM23ICGNtPA6ZoD9GZS/mE+uk+jSOzOk/96V9ObyhLFOTKnok6QUR+aiht86bWM1nMhAUEsTtvwZ8uhWBNBEWdG6icscdHZX1c1RM7GOil8EqapXQJ9UGoWoGAjXvim8H8HWmD5Ws9K/hQLWU7R36AYhQBarvDoqKUhmr+phXg4/y0TFqTd4VFCkv/Pl9Kstl2DIhUd75HUYoCT5j49sjOateWHxBCCdD/0skf8VThtleIu4f9XEA0BHGFroMbccCeupYS0Air9mZZAZd5ZArBPWGTWBQIeo8+MJnvnusY5wAJDV/OZeBk8NL40I6pCw3P/4+HZSSrYt/JbhxEeh/p8QAOI7snBgGp/OcyDpBXzH0GhC9YavL1JOY8AxPdlcNDaxCImUkzObTxSmOz8PQnGc99vyKcKb+BJis0G0jGBGQ+s9VhODy4DgWzrbmGlG6n6FU2yIDxIlxcSF089EtSRsY4hcMfFWi8Zui8XCHU6XYnd87BxCprwS5RjMVYw+8XyW9H0bZKvWTHm5EXNJVt0LFwEPFipnGu0WCSdBX8RnzhFlJuieW1wJcXfNc83FqCPmMZiuLn643DTSyEcKEMJkABRn0r0hCsn6g+FIDucGoYXqOR9v13TuKGlRN3LdJsJfaWfkPVxey7GU6LqLgpON+QG2YG2y0cpg==
  template:
    metadata:
      creationTimestamp: null
      name: books-pipeline-secret
      namespace: books-pipeline
    type: Opaque
