---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: books-pipeline-secret
  namespace: books-pipeline
spec:
  encryptedData:
    BOOKS_DB_PASSWORD: AgBe2L0fRhpquBdrF89ehNwNHBLs7YBJOhtisgGt/mXs57m1o0Fw/bz0TLiRLhLtN/pp/JPbklIDNln1meCXthf2KrKM23ICGNtPA6ZoD9GZS/mE+uk+jSOzOk/96V9ObyhLFOTKnok6QUR+aiht86bWM1nMhAUEsTtvwZ8uhWBNBEWdG6icscdHZX1c1RM7GOil8EqapXQJ9UGoWoGAjXvim8H8HWmD5Ws9K/hQLWU7R36AYhQBarvDoqKUhmr+phXg4/y0TFqTd4VFCkv/Pl9Kstl2DIhUd75HUYoCT5j49sjOateWHxBCCdD/0skf8VThtleIu4f9XEA0BHGFroMbccCeupYS0Air9mZZAZd5ZArBPWGTWBQIeo8+MJnvnusY5wAJDV/OZeBk8NL40I6pCw3P/4+HZSSrYt/JbhxEeh/p8QAOI7snBgGp/OcyDpBXzH0GhC9YavL1JOY8AxPdlcNDaxCImUkzObTxSmOz8PQnGc99vyKcKb+BJis0G0jGBGQ+s9VhODy4DgWzrbmGlG6n6FU2yIDxIlxcSF089EtSRsY4hcMfFWi8Zui8XCHU6XYnd87BxCprwS5RjMVYw+8XyW9H0bZKvWTHm5EXNJVt0LFwEPFipnGu0WCSdBX8RnzhFlJuieW1wJcXfNc83FqCPmMZiuLn643DTSyEcKEMJkABRn0r0hCsn6g+FIDucGoYXqOR9v13TuKGlRN3LdJsJfaWfkPVxey7GU6LqLgpON+QG2YG2y0cpg==
    N8N_WEBHOOK_URL: AgCgRzOKzMw8Ukkn1L/xiQDmg40APHQ8GDTzjLWy5B1Hfde2IxO3Wjw9DIzCW2zhsSpE87a8WB8+D3OXV4Imcv8hwMabLClNFFEieqteDvktxW3R/BUsSoALQM++ovDHNjKOuJDniTA/lrYPT6BV7uYC4AlXLNHBKqMVZDZDgy0XHQ/MaaDVhFYTUJ24BzYbVAmK9QDO9uBZVy8WlZ0fk7WvpXwEUHb4/gK3DL/2Nb+BuNSvhwXaO8WyRUBvfOoFIq8wxtM91kd6SB82u9tEy1wjsM5ybi5PdeHkxIIYo4CAZQemUeNMFafeaG+eblV4Y00s/RteEaLN8FU1wrueJoY+8ihgaP/siF6mx3QIJH1jWBC94alcN6nnhrKrjpBK7LI6hSpoPagp3mmO6o3+WzpM6mCR9W1+OzmVww0P+gBOB1vHk0cIdFebz8kXORmxwp3CDv3f5+sFMA2MA8ZtPrEtJpgEQhNpx5SHNrxDo34dheXWrFAYQ4pcZfEbqTWMw+xXxlS+h6pZnjFNESvFrv39sLx/0qbWdblWUH8gMJl/CIda1u0Co/Y3FIzFtUoLjmtxsXsbbaWdsr7mW+PgVFKWey9d/0n9TtTyH8UD/zFRXWTJO033a2m+odhzBWLN4k3lpd4pPULb9TBR9DHC+AuXlQprxid/zGrBrOrobGZMzfPHUgl3Z6GrEf6qiVuvZdmVise+U78qhFqutCeZVmoaEQqOP9KD8Ct8ojiNG/R6mmRYZNlx59Zax0e7sKmvz9iGf9yqIR6tg6qd
  template:
    metadata:
      creationTimestamp: null
      name: books-pipeline-secret
      namespace: books-pipeline
    type: Opaque
