---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openwebui-anthropic
  namespace: open-webui
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgBr6ztLSf42So4mXgyTSP55frDZRe8TLwEMHtNOpuca240T2UuGwU+r3+H0qQIbRWdMF8A9ENf0IAQR64Wmqipk0bv8AesUFI0XExgK7MvsbIVauu68BqQ3xdL/FCGl9dcfuami0XIznKQ362TOw+m/7gf9LVaHXIAkHRnoBi+gYC/X/cXafl2k+A0OpjkXHxqNEE1KqZR3LhFjLLymMSRUycNERxGcCF7ElqufSvl1K+cJhIUvZ5z8CUaMJ1aBt4pCBoAY69cUEv7KdGMDBwmfZrH5yc7zUvZ1qrl3WjiZoxYLccdUxAu9dHWPzVRQkeApkOVnyi2c0W17hi6cYIejmDH8g+O1uc3FX6Diz4H9TKA6sHEcyss5z6+pfMbpMhlRV+N2Bgt3LLmGlJdCkUA8Rb6WchsXXEFJONbzPJWaWULFlEEFfmPbKzxLQz+tQJ8Wyo5xRHarzwhkfgeE/E+Sur6ErrFXIiakIEvxTOCcZpKdrpqEmrFsQSOWTCaCFGBcX+dUAaHTjsmq4dc9mkQmT37TvLiCDkq0XRXMJRveSqZzFq6KNtdHEV6kix5sF9h+DV6nb4gHSJJW7hFdXEyq1sZUwwfnqY5qkqS/YaRTtj1pU2TjbZjUFzhX17Nn24IN76F4WgmSdR5h0IzK65A+peGaida6Fc/eAHAbcVzju5reF2CDbYXmWuGY7bT8gpsoiirx0q2985oEmMolV0tuanK6X105ZhKxhfDkFUHxAkG8kWKHsfHACz4eJqKFitaMWctO3l2WslGPry3Iugb1bkCxXh+1vctPYtMRPNy7ODN38Z8OM6+vbX3ntd2pLDgVxw39wiVq+0x2ndw=
  template:
    metadata:
      creationTimestamp: null
      name: openwebui-anthropic
      namespace: open-webui
