apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-webui

resources:
  - litellm-sealed-secret.yml
  - app-sealed-secret.yml
  - open-webui-pvc.yml
  - open-webui-deployment.yml
  - open-webui-service.yml
  - open-webui-ingress.yml
