---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openwebui-litellm
  namespace: open-webui
spec:
  encryptedData:
    LITELLM_API_KEY: AgAbS2uQWulfLezd9puXGaFR6yGW7ISWW7QNqGUvzqOOOTU4Q2s6uKUumXXZnChQZbHor8ReFYh+A9ydBQ3Fk6Qe3Z8S87f6PK9LID7pxHf2l3DOzsm+SMFnIvtGcefFJ+Un3Ctwp2vO3Ba/rO2Mq6IsQx/bmd9C4+nr9+uolOB2UjG6gHufHOx+pbDnxnfwcy7ZIUPop0aAReWUeT3zNvh/HAFxxwPV614Po/S4+kX4NPB+sp7htaq4kAMGeiIkbAbRkj91XdWbpWgCEYKbD8V7yBY8IF0SmHb0hP70hN8UoIk2xq5Rueai7wzeMOJOM+IqASrnPV2sTT/DnADNM/XGzhFSIwiJ+0M4u/rjVhzegNtkzuic+IHUFe+1hWhQFiO09bzJO/KKCDVyydkkrwQgcFM3sA1ZGLGMxIqWkUGt4c3/8relPF5XhLoJi0E3Zwl7lVQBa2+yI/obSL3raoFHUmrUek3aDoJVGIwnD/HMlDrpB35VFa44bj8DQTgYP0p+sY4Wl6BwoANaTvKqEwgy96nqYtHcf81Q+0eP9983G3i0OXR5pvSmqDNSSzmeVS/NqLq1cNgeBE4dL+Mblgf40qrrSOWrzgifULfU/e9pCtEr5KjI0KdZKevYv2Qi3jby9OZXTSiEFFlx7tDm9OqGZ2Atxd864ZjsRdJXlacTM+XPbQoSj+SE9hbYBjUHbMqD/20fzFU8NhGYQzVQDML+ZfWxoTCO/XAvo8jMT6jxox4cr6eYbs0VK/z9XOksVCuInYM=
  template:
    metadata:
      creationTimestamp: null
      name: openwebui-litellm
      namespace: open-webui
