apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - novnc-namespace.yml
  - novnc-deployment.yml
  - novnc-service.yml
  - novnc-middleware.yml
  - novnc-ingress.yml
  - novnc-certificate.yml
