apiVersion: v1
kind: ConfigMap
metadata:
  name: novnc-tokens
  namespace: remote-access
  labels:
    app: novnc
    argocd.argoproj.io/managed-by: argocd
data:
  tokens.cfg: |
    mac: 192.168.2.163:5900
