apiVersion: v1
kind: ConfigMap
metadata:
  name: novnc-tokens
  namespace: remote-access
  labels:
    app: novnc
    app.kubernetes.io/name: novnc
    app.kubernetes.io/component: remote-access
    argocd.argoproj.io/managed-by: argocd
data:
  tokens.cfg: |
    desktop: 192.168.2.163:5900
