apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novnc
  namespace: remote-access
  labels:
    app: novnc
    app.kubernetes.io/name: novnc
    argocd.argoproj.io/managed-by: argocd
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: remote-access-novnc-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - novnc.i3sec.com.au
    secretName: novnc-tls
  rules:
  - host: novnc.i3sec.com.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: novnc
            port:
              number: 80
