apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: novnc-tls
  namespace: remote-access
  labels:
    app: novnc
    argocd.argoproj.io/managed-by: argocd
spec:
  secretName: novnc-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - novnc.lan
  ipAddresses:
    - 192.168.2.10
