apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: novnc-redirect
  namespace: remote-access
  labels:
    app: novnc
    argocd.argoproj.io/managed-by: argocd
spec:
  redirectRegex:
    regex: "^(https?://[^/]+)/?$"
    replacement: "${1}/vnc.html?autoconnect=true&path=websockify%3Ftoken%3Dmac"
    permanent: true
